<?php

namespace AppBundle\Repository;

/**
 * RequestStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestStructureRepository extends \Doctrine\ORM\EntityRepository
{
}
