<?php

namespace AppBundle\Repository;

/**
 * TicketCreationCallLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCreationCallLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
